# Currently, there is nothing that can be built under this directory.
#
# Due to the recursive nature of the top-level Makefile, however, we run into
# an issue if we drill into this folder. This Makefile acts as a placeholder,
# then, in order to allow the build process to move along instead of aborting
# with an error.
#

all:
	@echo "Nothing to build in contrib/... Moving on."
