mfm_sources_1 = files(
  'analyze.c',
  'board.c',
  'corvus_mfm_decoder.c',
  'crc_ecc.c',
  'deltas_read.c',
  'drive.c',
  'drive_read.c',
  'emu_tran_file.c',
  'mfm_decoder.c',
  'mfm_read.c',
  'msg.c',
  'northstar_mfm_decoder.c',
  'parse_cmdline.c',
  'perq_mfm_decoder.c',
  'pru_setup.c',
  'tagged_mfm_decoder.c',
  'wd_mfm_decoder.c',
  'xebec_mfm_decoder.c',
)

mfm_utils_src = files(
  'analyze.c',
  'corvus_mfm_decoder.c',
  'crc_ecc.c',
  'deltas_read_file.c',
  'drive_file.c',
  'emu_tran_file.c',
  'mfm_decoder.c',
  'mfm_util.c',
  'msg.c',
  'northstar_mfm_decoder.c',
  'parse_cmdline.c',
  'perq_mfm_decoder.c',
  'tagged_mfm_decoder.c',
  'wd_mfm_decoder.c',
  'xebec_mfm_decoder.c',
)

mfm_sources_3 = files(
  'board.c',
  'crc_ecc.c',
  'drive.c',
  'drive_write.c',
  'emu_tran_file.c',
  'mfm_write.c',
  'msg.c',
  'parse_cmdline_write.c',
  'pru_setup.c',
)

find_crc_info_src = files('find_crc_info.cpp')

mfm_include = include_directories('inc')
